'use client'

import { useEffect, useState, useTransition } from 'react'
import { Database, Plus, Trash2 } from 'lucide-react'
import { getBackendModelAction, saveBackendModelAction } from '@/app/actions/projects'
import type { ProjectSpecification } from '@/lib/project-specification'

type Entity = ProjectSpecification['data']['entities'][number]
type Field = Entity['fields'][number]
const FIELD_TYPES: Field['type'][] = ['text','number','boolean','date','datetime','email','url','image','file','relation','json']
function identifier(value:string,fallback:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').replace(/^[^a-z]+/,'')||fallback}

export function BackendWorkspace({projects}:{projects:Array<{id:string;name:string}>}){
  const [projectId,setProjectId]=useState(projects[0]?.id??'');const [entities,setEntities]=useState<Entity[]>([]);const [entityName,setEntityName]=useState('');const [message,setMessage]=useState<string|null>(null);const [loading,setLoading]=useState(Boolean(projectId));const [pending,startTransition]=useTransition()
  useEffect(()=>{if(!projectId)return;let active=true;getBackendModelAction(projectId).then(spec=>{if(active)setEntities(spec.data.entities)}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:'Data model could not be loaded.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[projectId])
  function selectProject(value:string){setProjectId(value);setEntities([]);setMessage(null);setLoading(Boolean(value))}
  function addEntity(){const name=entityName.trim();if(!name)return;const base=identifier(name,'entity');let id=base,suffix=2;while(entities.some(entity=>entity.id===id))id=`${base}-${suffix++}`;setEntities(current=>[...current,{id,name,fields:[]}]);setEntityName('')}
  function addField(entityId:string){setEntities(current=>current.map(entity=>{if(entity.id!==entityId)return entity;let id='field',suffix=2;while(entity.fields.some(field=>field.id===id))id=`field-${suffix++}`;return{...entity,fields:[...entity.fields,{id,name:'New field',type:'text',required:false}]}}))}
  function updateField(entityId:string,fieldId:string,values:Partial<Field>){setEntities(current=>current.map(entity=>entity.id===entityId?{...entity,fields:entity.fields.map(field=>field.id===fieldId?{...field,...values}:field)}:entity))}
  function save(){setMessage(null);startTransition(async()=>{const result=await saveBackendModelAction(projectId,entities);setMessage(result.ok?`Saved ${entities.length} ${entities.length===1?'entity':'entities'} and generated ${result.files.join(' and ')}.`:result.error)})}
  return <><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Backend</h1><p className="mt-1 text-sm text-[#806b60]">Design a persisted data model and generate executable PostgreSQL plus TypeScript artifacts.</p></div><select aria-label="Backend project" value={projectId} onChange={event=>selectProject(event.target.value)} className="h-10 rounded-xl border border-[#eadfd8] bg-white px-3 text-sm dark:border-white/10 dark:bg-[#211b18]"><option value="">Select project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></div>
    {!projectId?<div className="mt-8 rounded-2xl border border-dashed p-10 text-center text-sm text-[#806b60]">Select an active project to edit its backend model.</div>:<div className="mt-7 grid gap-5"><section className="rounded-2xl border border-[#eadfd8] bg-white p-5 dark:border-white/10 dark:bg-white/5"><div className="flex items-center gap-2"><Database size={19} className="text-[#b87850]"/><h2 className="text-lg font-semibold">Data entities</h2></div><div className="mt-4 flex gap-2"><input aria-label="New entity name" value={entityName} onChange={event=>setEntityName(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')addEntity()}} placeholder="Booking, Customer, Product…" className="input min-w-0 flex-1"/><button type="button" onClick={addEntity} disabled={!entityName.trim()} className="inline-flex items-center gap-2 rounded-xl bg-[#332721] px-4 text-sm font-semibold text-white disabled:opacity-40"><Plus size={15}/>Add entity</button></div>{message&&<p role="status" className="mt-4 rounded-xl border border-[#eadfd8] bg-[#fff8f3] px-3 py-2 text-sm dark:border-white/10 dark:bg-white/5">{message}</p>}</section>
    {loading?<p className="text-sm text-[#806b60]">Loading data model…</p>:entities.length===0?<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-[#806b60]">No pretend tables are added. Create your first real entity above.</div>:entities.map(entity=><section key={entity.id} className="rounded-2xl border border-[#eadfd8] bg-white p-5 dark:border-white/10 dark:bg-white/5"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><input aria-label={`${entity.name} name`} value={entity.name} onChange={event=>setEntities(current=>current.map(item=>item.id===entity.id?{...item,name:event.target.value}:item))} className="text-lg font-semibold outline-none"/><p className="font-mono text-xs text-[#806b60]">{entity.id}</p></div><button type="button" onClick={()=>setEntities(current=>current.filter(item=>item.id!==entity.id))} aria-label={`Delete ${entity.name}`} className="rounded-lg p-2 text-red-600"><Trash2 size={16}/></button></div><div className="mt-4 space-y-2">{entity.fields.map(field=><div key={field.id} className="grid gap-2 rounded-xl border border-[#eadfd8] p-3 sm:grid-cols-[1fr_150px_120px_36px] dark:border-white/10"><input aria-label={`${entity.name} field name`} value={field.name} onChange={event=>updateField(entity.id,field.id,{name:event.target.value,id:identifier(event.target.value,field.id)})} className="input"/><select aria-label={`${field.name} type`} value={field.type} onChange={event=>{const type=event.target.value as Field['type'];updateField(entity.id,field.id,{type,relationEntityId:type==='relation'?(entities.find(item=>item.id!==entity.id)?.id??entity.id):undefined})}} className="input">{FIELD_TYPES.map(type=><option key={type}>{type}</option>)}</select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={field.required} onChange={event=>updateField(entity.id,field.id,{required:event.target.checked})}/>Required</label><button type="button" aria-label={`Delete ${field.name}`} onClick={()=>setEntities(current=>current.map(item=>item.id===entity.id?{...item,fields:item.fields.filter(candidate=>candidate.id!==field.id)}:item))} className="text-red-600"><Trash2 size={15}/></button>{field.type==='relation'&&<select aria-label={`${field.name} related entity`} value={field.relationEntityId} onChange={event=>updateField(entity.id,field.id,{relationEntityId:event.target.value})} className="input sm:col-span-4">{entities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}</div>)}</div><button type="button" onClick={()=>addField(entity.id)} className="mt-3 inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold"><Plus size={13}/>Add field</button></section>)}
    <button type="button" onClick={save} disabled={pending||loading||entities.length===0} className="justify-self-start rounded-xl bg-[#e98b66] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{pending?'Generating…':'Save model & generate backend files'}</button></div>}</>
}
