import type { ProjectSpecification } from '@/lib/project-specification'

const sqlTypes: Record<ProjectSpecification['data']['entities'][number]['fields'][number]['type'], string> = {
  text: 'text', number: 'double precision', boolean: 'boolean', date: 'date', datetime: 'timestamptz',
  email: 'text', url: 'text', image: 'text', file: 'text', relation: 'uuid', json: 'jsonb',
}

const tsTypes: Record<ProjectSpecification['data']['entities'][number]['fields'][number]['type'], string> = {
  text: 'string', number: 'number', boolean: 'boolean', date: 'string', datetime: 'string',
  email: 'string', url: 'string', image: 'string', file: 'string', relation: 'string', json: 'unknown',
}

function quote(value: string) { return `"${value.replaceAll('"', '""')}"` }
function interfaceName(value: string) {
  const result = value.normalize('NFKD').replace(/[^a-zA-Z0-9]+(.)/g, (_, next: string) => next.toUpperCase()).replace(/^[^a-zA-Z]+/, '')
  return result ? result[0].toUpperCase() + result.slice(1) : 'Model'
}

export function generateBackendArtifacts(specification: ProjectSpecification) {
  if (specification.data.entities.length === 0) throw new Error('Add at least one data entity before generating backend files.')
  const sql = [
    '-- Generated by Lucky Lotus. Review this migration before applying it.\nCREATE EXTENSION IF NOT EXISTS pgcrypto;',
    ...specification.data.entities.map(entity => {
      const fields = entity.fields.map(field => {
        const relation = field.type === 'relation' ? ` REFERENCES ${quote(field.relationEntityId!)}(id)` : ''
        return `  ${quote(field.id)} ${sqlTypes[field.type]}${field.required ? ' NOT NULL' : ''}${relation}`
      })
      return `CREATE TABLE IF NOT EXISTS ${quote(entity.id)} (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n${fields.length ? `${fields.join(',\n')},\n` : ''}  "createdAt" timestamptz NOT NULL DEFAULT now(),\n  "updatedAt" timestamptz NOT NULL DEFAULT now()\n);`
    }),
  ].join('\n\n') + '\n'
  const models = ['// Generated by Lucky Lotus from the persisted project data model.', ...specification.data.entities.map(entity => {
    const fields = entity.fields.map(field => `  '${field.id}'${field.required ? '' : '?'}: ${tsTypes[field.type]}`).join('\n')
    return `export interface ${interfaceName(entity.name)} {\n  id: string\n${fields ? `${fields}\n` : ''}  createdAt: string\n  updatedAt: string\n}`
  })].join('\n\n') + '\n'
  return [{ path: 'backend/schema.sql', content: sql }, { path: 'backend/models.ts', content: models }]
}
